import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CharacterStatistics from '@/components/DashboardComponent'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            This is a beautiful project designed to list &nbsp;
            <code className={styles.code}>characters</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
             Damilola Daramola
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.center}>
          <a
            href="/characters"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
             View All Characters <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Character List.
            </p>
          </a>
        </div>
        
          <div>
            <CharacterStatistics />
          </div>
        
      </main>
    </>
  )
}
